/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mortgageplan;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
    	Mortgageplan m = new Mortgageplan();
		m.printProspects();
		assertEquals("Prospects list should have four elements", 4, m.prospects.size());
		assertTrue(64 == Mortgageplan.pow(2, 6));
		assertTrue(14348907 == Mortgageplan.pow(3, 15));
		assertTrue(Mortgageplan.monthlyPayment(0.05, 1000, 2) == 72.47089977590733);
		assertTrue(Mortgageplan.monthlyPayment(0.0127, 4356, 6) == 92.67633606225289);
		assertTrue(Mortgageplan.monthlyPayment(0.0867, 1300.55, 2) == 130.49849354129998);
		assertTrue(Mortgageplan.monthlyPayment(0.06, 2000, 4) == 127.79530813706259);
    }
}
