/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mortgageplan;

public class App {
    public static void main(String[] args) {
    	Mortgageplan m = new Mortgageplan();
    	m.printProspects();
    }
}
